import {
  Img1,
  Img2,
  Img3,
  Img5,
  Img6,
  Img8,
  Img9,
  Roti1,
  Img10,
  Img11,
  Img12,
  Img13,
  maincarrot,
  Kiwi,
  Img14,
  Img15,
  Img16,
  Img17,
  Apple,
  Img18,
  Img19,
  chickens,
  Img20,
  Img20r,
  curd1,
  curd2,
  Idly,
  Idly2,
  Thali,
  Thali1,
  Thali2,
  Shawrma1,
  Shawrma2,
  Burgur,
  Burgur2,
  Chicken,
  Chicken2,
  tom,
  tom2,
  tom3,
  on,
  on2,
  on1,
  carrot3,
  carrots,
  chicken,
  chicken2,
  carrot,
  lady,
  ladys,
  bone1,
  bone2,
  mutton1,
  mutton2,
  chickens1,
  chickens2,
  chick1,
  chick2
} from "../img/index";



//  Dairy

import eggs from "../img/new/eggs.webp";
import eggs2 from "../img/new/eggs2.webp";
import fssai from "../img/new/sai.jpeg";

// Essentials

import beerShampoo1 from "../img/essentials/beershampo.webp";
import beerShampoo2 from "../img/essentials/beershampo2.webp";






export const OfferCardData = [
  {
    id: 112,
    name: "We Deliver The Best Coffee",
    imgUrl : "https://www.shadevelopers.com/wp-content/uploads/2023/03/coffee.webp" ,
    description: "Fresh Coffee is The Place Where You Can Find the Best Coffee in this Whole Towm ! We Highly Recommend to Visit This Coffee Shop With Your Family Members",
    home:"Home Delivery Available",
     
  },
   
   
]


export const items = [
  // Home Essentials
  {
    id: 24,
    category: "essentials",
    cuisines: ["Antibiotic free", "Rich in omega 3 ", "Carefully selected "],
    img: beerShampoo1,
    description: " Park Avenue Beer Shampoo",
    price: 422,
    actualPrice: 650,
    isVegetarian: false,
    otherImgs: [beerShampoo2, beerShampoo2],
    specs:
      "This richly lathering shampoo is packed with Real Beer which has excellent conditioning properties. It has the goodness of Barley and hops which are rich in proteins and Vitamin B.",
    texture: "50% off upto ₹100",
    weight: "Bhimavaram",
    size: "  Deliver in 30 mins",
  },

  //  Dairy Items

  {
    id: 23,
    category: "dairy",
    cuisines: ["Antibiotic free", "Rich in omega 3 ", "Carefully selected "],
    img: eggs,
    description: "Fresho Farm Eggs 6pcs",
    price: 46,
    actualPrice: 65,
    isVegetarian: false,
    otherImgs: [eggs2, fssai],
    specs:
      "Eggs are one of the common food items in most of the households. From breakfast to dinner, eggs are indulged in various ways. Poached, boiled, fried; we all have our own favourite choices. Not only are they delicious, but they are also crammed with health benefits. It is one of the most in-expensive sources of high protein. These are one of nature's most wholesome and cost-effective foods. An egg can give you a health kick in no time at all! It is the ideal ingredient to add to your child's breakfast for growth and development. ",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "  Deliver in 60 mins",
  },

  //

  //  Vegetable Section

  {
    id: 11,
    category: "vegetables",
    cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
    img: lady,
    description: "Ladys Finger",
    price: 40,
    actualPrice: 50,
    isVegetarian: true,
    otherImgs: [lady, ladys],
    specs:
      "The Here Comes The Sun pendant designed by Bertrand Balas is a quality lamp with a unique and magical look. The Here Comes The Sun series has a fantastic expression and especially swhen turned on it creates a very special atmosphere in the room it hangs in. The lamp fits perfectly above both dining room table, kitchen counter, and as living room lighting . ",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "  Deliver in 26 mins",
  },
  {
    id: 12,
    category: "vegetables",
    DeliveryTime: "30 mins",
    cuisines: ["Carrots", "Vegetables"],
    img: maincarrot,
    isVegetarian: true,
    description: "Ooty Carrot",
    price: 220,
    actualPrice: 200,
    otherImgs: [carrots, carrot3],
    specs:
      "Ooty Carrot is a premium variety of carrots grown in the pristine hills of Ooty. Known for its vibrant orange color and sweet flavor, Ooty Carrot is a favorite among carrot lovers. It is rich in beta-carotene, vitamin A, and dietary fiber, making it a nutritious addition to your meals. Use Ooty Carrot in salads, stir-fries, or as a healthy snack option.",
    texture: "Crunchy and sweet",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 13,
    category: "vegetables",
    DeliveryTime: "30 mins",
    cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
    isVegetarian: true,
    img: tom2,
    description: "Tomato",
    price: 33,
    actualPrice: 30,
    otherImgs: [tom, tom3],
    specs:
      "Tomato is a versatile and essential vegetable in many cuisines. It is known for its vibrant red color, juicy texture, and tangy flavor. Tomatoes are rich in vitamins A and C, antioxidants, and other beneficial nutrients. They are commonly used in salads, sauces, soups, and various cooked dishes. Enjoy the freshness and taste of tomatoes in your favorite recipes.",
    texture: "Juicy and tangy",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 15,
    category: "vegetables",
    DeliveryTime: "30 mins",
    isVegetarian: true,
    img: on,
    cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
    isVegetarian: true,
    description: "Onion",
    price: 330,
    actualPrice: 300,
    otherImgs: [on1, on2],
    specs:
      "Onion is a versatile vegetable used in various culinary preparations. It adds flavor and aroma to dishes and can be enjoyed raw or cooked. Onions come in different varieties, each with its own distinct taste and texture. They are rich in antioxidants and have health benefits. Incorporate onions into your recipes to enhance their taste and nutritional value.",
    texture: "Crunchy and flavorful",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  // Food Items  ?

  {
    id: 1,
    category: "food",
    DeliveryTime: "30 mins",
    img: curd1,
    rating: 4.5,
    cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
    isVegetarian: true,
    description: "Special Curd Rice",
    price: 100,
    actualPrice: 120,
    otherImgs: [Img1, curd2],
    specs:
      "This Curd Rice is a hearty and flavorful dish that combines rice with a variety of ingredients to create a satisfying meal. The dish typically includes yogurt, cooked rice, and tempered with spices like mustard seeds, curry leaves, and asafoetida. Whether you're looking for a quick and refreshing meal or a comforting side dish, Curd Rice is sure to hit the spot.",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 2,
    category: "food",
    DeliveryTime: "30 mins",
    rating: 4.5,
    img: Img2,
    cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
    isVegetarian: true,
    description: "Idly Vada Special",
    price: 45,
    actualPrice: 60,
    otherImgs: [Idly, Idly2],
    specs:
      "Idly and vada are two popular South Indian breakfast dishes. Idly is a soft, steamed rice cake made from fermented batter, while vada is a crispy, savory doughnut-shaped fritter made from lentil batter. They are often served together, along with chutneys and sambar, a lentil-based soup. Enjoy this classic combination for a wholesome and delicious breakfast.",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 3,
    category: "food",
    DeliveryTime: "30 mins",
    img: Thali,
    rating: 1.5,
    cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
    isVegetarian: true,
    description: "Indian Thali",
    price: 250,
    actualPrice: 300,
    otherImgs: [Thali1, Thali2],
    specs:
      "Indian thali is a traditional meal served on a large platter, consisting of a variety of dishes, often including rice, bread, curries, vegetables, dal, yogurt, chutney, and dessert. It is a complete and balanced meal that offers a range of flavors, textures, and nutrients. Thalis vary from region to region in India, reflecting the local cuisine and culture.",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 4,
    category: "food",
    DeliveryTime: "30 mins",
    img: Roti1,
    cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
    isVegetarian: true,
    description: "Chapati",
    price: 80,
    actualPrice: 100,
    otherImgs: [Roti1, Roti1],
    specs:
      "Chapati is a staple flatbread in Indian cuisine, made from whole wheat flour, water, and salt. It is typically cooked on a tawa, a flat griddle, and served hot with a variety of curries, vegetables, and lentils. Chapatis are an essential part of the Indian diet and are often eaten for breakfast, lunch, and dinner. Enjoy the soft and fluffy texture of freshly made chapatis.",
    texture: "Free Delivery",
    weight: "Bhimavaram",
    size: "Deliver in 20 mins",
  },
  {
    id: 5,
    category: "food",
    DeliveryTime: "30 mins",
    img: Img5,
    cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
    description: "Roti",
    price: 189,
    actualPrice: 200,
    otherImgs: [Roti1, Roti1],
    specs:
      "Roti is a staple flatbread in Indian cuisine, made from whole wheat flour, water, and salt. It is typically cooked on a tawa, a flat griddle, and served hot with a variety of curries, vegetables, and lentils. Roti is a versatile bread that complements a wide range of dishes and adds a wholesome element to your meal.",
    texture: "Plastic",
    weight: "3kg",
    size: "20cm x 20cm",
  },
  {
    id: 6,
    category: "food",
    DeliveryTime: "30 mins",
    img: Img13,
    cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
    description: "Chicken Shawarma",
    price: 200,
    actualPrice: 250,
    otherImgs: [Shawrma2, Shawrma1],
    specs:
      "Chicken shawarma is a Middle Eastern dish made from marinated chicken that is slowly roasted on a spit and shaved off as it cooks. The chicken is typically served in a pita bread with a variety of accompaniments, such as tomatoes, lettuce, onions, pickles, and tahini sauce. Chicken shawarma is a flavorful and satisfying meal that is popular around the world.",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 7,
    category: "food",
    DeliveryTime: "30 mins",
    img: Img10,
    cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
    description: "Indian Burger",
    price: 220,
    actualPrice: 270,
    otherImgs: [Burgur, Burgur2],
    specs:
      "Burgers are a popular fast food item enjoyed worldwide. They consist of a grilled or fried patty made from ground meat or plant-based ingredients, placed inside a bun, and topped with various ingredients such as lettuce, tomatoes, cheese, onions, and sauces. Indian burgers often incorporate spices and flavors inspired by the local cuisine, creating a unique twist on this classic dish.",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 8,
    category: "food",
    DeliveryTime: "30 mins",
    img: Img8,
    cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
    description: "Special Chicken Curry",
    price: 115,

    actualPrice: 150,
    otherImgs: [Chicken, Chicken2],
    specs:
      "Chicken curry is a popular dish in many cuisines around the world. It typically involves cooking chicken pieces in a flavorful sauce made from a combination of spices, herbs, onions, tomatoes, and other ingredients. The dish can be customized with various levels of spiciness and can be enjoyed with rice, bread, or other accompaniments. Indulge in the rich and aromatic flavors of this special chicken curry.",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  // {
  //   id: 9,
  //   category: "food",
  //   DeliveryTime: "30 mins",
  //   img: Biryani1,
  //   cuisines: ["Desserts", "Ice Cream", "Vegetables", "Food-Item"],
  //   description: "Chicken Biryani",
  //   price: 250,
  //   actualPrice: 300,
  //   otherImgs: [Biryani1, Biryani1],
  //   specs:
  //   "Chicken biryani is a classic Indian dish that features aromatic basmati rice cooked with succulent chicken pieces and a blend of spices. The dish is layered with fried onions, saffron-infused milk, and garnished with fresh coriander leaves. Chicken biryani is a flavorful and satisfying meal that is enjoyed on special occasions or as a hearty meal during gatherings with family and friends.",
  //   texture: "50% off upto ₹200",
  //   weight: "Bhimavaram",
  //   size: "Deliver in 26 mins"
  // },

  // fruit Section-  14 to 18-------------------------------------------------------
  {
    id: 14,
    category: "fruits",
    DeliveryTime: "30 mins",
    img: Img14,
    isVegetarian: true,
    cuisines: ["Desserts", "Ice Cream", "Fruits", "Food-Item"],
    description: "Oak Spanish Chair",
    price: 520,
    actualPrice: 728,
    otherImgs: [Img14, Img14],
    specs:
      "The Oak Spanish Chair is a beautifully designed piece by Børge Mogensen, known for its elegance and craftsmanship. It is one of his most recognized products worldwide, blending traditional Spanish influences with Danish design sensibilities. The chair features high-quality oak wood and a comfortable seat, making it a perfect addition to any living space.",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 16,
    category: "fruits",
    DeliveryTime: "30 mins",
    img: Img16,
    cuisines: ["Desserts", "Ice Cream", "Fruits", "Food-Item"],
    isVegetarian: true,
    description: "Bananas",
    price: 120,
    actualPrice: 168,
    otherImgs: [Img16, Img16],
    specs:
      "Bananas are a nutritious fruit that is widely enjoyed for its taste and health benefits. They are rich in potassium, vitamin C, and dietary fiber. Bananas are known for their natural sweetness and creamy texture, making them a versatile ingredient in various dishes and smoothies. They are also a convenient on-the-go snack option. Enjoy the goodness of bananas with this fresh and delicious fruit.",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 17,
    category: "fruits",
    DeliveryTime: "30 mins",
    img: Img17,
    cuisines: ["Desserts", "Ice Cream", "Fruits", "Food-Item"],
    isVegetarian: true,
    description: "Strawberries",
    price: 75,
    actualPrice: 105,
    otherImgs: [Img17, Img17],
    specs:
      "Strawberries are sweet and juicy fruits that are loved by people of all ages. They are packed with essential nutrients, including vitamins, minerals, and antioxidants. Strawberries can be enjoyed on their own, added to salads, or used in various desserts. Their vibrant red color and refreshing taste make them a delightful treat. Experience the goodness of fresh strawberries with this high-quality product.",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 18,
    category: "fruits",
    DeliveryTime: "30 mins",
    img: Img18,
    isVegetarian: true,
    cuisines: ["Desserts", "Ice Cream", "Fruits", "Food-Item"],
    description: "Mangoes",
    price: 175,
    actualPrice: 245,
    otherImgs: [Img18, Img18],
    specs:
      "Mangoes are known as the king of fruits and are loved for their sweet and tropical flavor. They are rich in vitamins A and C, as well as dietary fiber. Mangoes can be enjoyed on their own, added to fruit salads, or used in smoothies and desserts. Indulge in the luscious taste of ripe mangoes with this high-quality product.",
    texture: "50% off upto ₹200",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 9,
    category: "fruits",
    DeliveryTime: "30 mins",
    img: Kiwi,
    cuisines: ["Desserts", "Ice Cream", "Fruits", "Food-Item"],
    isVegetarian: true,
    description: "Kiwi",
    price: 161,
    actualPrice: 225.4,
    otherImgs: [Kiwi, Kiwi],
    specs:
      "Kiwis are small, green fruits with a fuzzy brown exterior and bright green flesh. They are packed with vitamin C, vitamin K, and dietary fiber. Kiwis have a unique tangy-sweet flavor and are often used in fruit salads, smoothies, and desserts. Enjoy the refreshing taste and health benefits of kiwis with this high-quality product.",
    texture: "40% off upto ₹300",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },
  {
    id: 10,
    category: "fruits",
    DeliveryTime: "30 mins",
    img: Img14,
    cuisines: ["Desserts", "Ice Cream", "Fruits", "Food-Item"],
    isVegetarian: true,
    description: "Nagpur Oranges",
    price: 89,
    actualPrice: 124.6,
    otherImgs: [Img14, Img14],
    specs:
      "Nagpur Oranges are famous for their sweet and tangy flavor. They are rich in vitamin C and are known for their juiciness. Nagpur Oranges have a vibrant orange color and are often enjoyed as a snack or used in fresh juices. Experience the goodness of these delicious oranges with this high-quality product.",
    texture: "Wood",
    weight: "8kg",
    size: "🕒 Deliver in 20mins",
  },
  {
    id: 56,
    category: "fruits",
    DeliveryTime: "30 mins",
    img: Apple,
    cuisines: ["Desserts", "Ice Cream", "Fruits", "Food-Item"],
    isVegetarian: true,
    description: "Shimla Apple",
    price: 89,
    actualPrice: 124.6,
    otherImgs: [Apple, Apple],
    specs:
      "Shimla Apples are known for their crisp texture and sweet-tart flavor. They are rich in antioxidants and dietary fiber, making them a healthy choice for snacking. Shimla Apples have a bright red skin and a juicy flesh that is perfect for enjoying fresh or using in various recipes. Taste the freshness of Shimla Apples with this high-quality product.",
    texture: "Use Paytm Card",
    weight: "Bhimavaram",
    size: "Deliver in 26 mins",
  },

  //  Meat Section

  {
    id: 19,
    category: "meat",
    DeliveryTime: "30 mins",
    img: Img19,
    cuisines: ["Chicken", "Pork", "Beef"],
    isVegetarian: false,
    description: "Family Chicken",
    price: 119,
    otherImgs: [chick1, chick2],
    specs:
      "Family Chicken is a delicious and juicy chicken dish perfect for family meals. It is made with tender chicken pieces seasoned with a special blend of spices and cooked to perfection. Enjoy the rich flavors and succulent texture of this mouthwatering dish.",
    texture: "Juicy and tender",
    weight: "500g",
    size: "Deliver in 30 mins",
  },
  {
    id: 20,
    category: "meat",
    DeliveryTime: "30 mins",
    img: Img20,
    cuisines: ["Lamb", "Goat"],
    isVegetarian: false,
    description: "Mutton",
    price: 45,
    otherImgs: [bone1, bone2],
    specs:
      "Mutton is meat obtained from mature sheep, typically over the age of one year, and has a distinct flavor compared to lamb. It is a rich source of protein, iron, and vitamin B12, but can be higher in fat and calories than other meats. Enjoy the robust taste and nutritional benefits of this premium mutton.",
    texture: "Rich and flavorful",
    weight: "250g",
    size: "Deliver in 30 mins",
  },
  {
    id: 21,
    category: "meat",
    DeliveryTime: "30 mins",
    cuisines: ["Lamb", "Goat"],
    img: Img20r,
    isVegetarian: false,
    description: "Boneless Mutton",
    price: 45,
    otherImgs: [mutton2, mutton1],
    specs:
      "Boneless Mutton is a versatile and convenient option for your cooking needs. Made from tender cuts of mutton without bones, it offers the same rich flavor and nutritional benefits as regular mutton. Use it in various dishes and enjoy the succulent texture and mouthwatering taste.",
    texture: "Tender and succulent",
    weight: "250g",
    size: "Deliver in 30 mins",
  },
  {
    id: 22,
    category: "meat",
    DeliveryTime: "30 mins",
    img: chicken,
    cuisines: ["Chicken"],
    isVegetarian: false,
    description: "Chicken",
    price: 45,
    otherImgs: [chickens1, chickens2],
    specs:
      "Chicken is a versatile and popular meat choice loved by many. It is known for its tender texture and mild flavor that pairs well with a variety of seasonings and cooking methods. Whether you're grilling, roasting, or stir-frying, our fresh and high-quality chicken will elevate your dishes.",
    texture: "Tender and juicy",
    weight: "500g",
    size: "Deliver in 30 mins",
  },
];
